import { Application } from "../Application";

describe("Application", () => {
	it("should run an application without crashing", () => {
		let app = new Application("test-app", "Autogenerated test app");
		app.run([]);
	});
	
});



