import path from "path";
import { Application } from "../Application.js";

describe("Application", () => {
	it("should run an application without crashing", () => {
		let app = new Application("test-app", "Autogenerated test app");
		app.run(["node", `${process.cwd()}${path.sep}index.js`]);
	});
	
});



