/*
Copyright © <BalaM314>, 2024.
This file is part of cli-app.
cli-app is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
cli-app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with cli-app. If not, see <https://www.gnu.org/licenses/>.

Contains a small test application.
*/

import { Application, Script } from "../../build/index.js";
import { runApp } from "./test-utils.js";




const app = new Application("test-app", "Autogenerated test app");
app.command("cmd1", "test command", (opts, app) => {
	fail(`Handler should not be called`);
}, false, {
	namedArgs: {
		namedarg1: {
			description: "test arg",
		},
	},
	unexpectedNamedArgCheck: "warn",
});

await runApp(app, [`--namedarg111`, `--namedarg1`]);
// script.run(process.argv);
